spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/mss?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
